config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'annuaire#index'
  resources :annuaire
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/annuaire.rb
class Annuaire < ApplicationRecord
	belongs_to :user
	validates :num_dept, presence: true
	validates :nom_dpt, presence: true
	validates :commune, presence: true
	validates :email, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 has_many :annuaires
end

app/controllers/annuaire_controller.rb
class AnnuaireController < ApplicationController
	before_action :get_id, only: [:show]
  def index
    if params[:term] # Si le paramètre  term existe, c-à-d quand l'utilisateur un nom dans le formulaire de recherche
      @annuaires = Annuaire.joins(:user).where("lower(#{:username}) LIKE '%#{params[:term].downcase}%'").all
    else
      @annuaires = Annuaire.all
    end
  end

  def new
  	@annuaire = Annuaire.new
  end

  def create
    @annuaire_user = User.find(current_user.id)
    @annuaire = Annuaire.new(annuaire_params)
    @annuaire.user = @annuaire_user
      if @annuaire.save
        flash[:success] = "Annuaire enregistré avec succès"
        redirect_to annuaire_index_path
      else
        flash[:notice] = "Erreur lors de validation, vérifier si les champs sont rempli correctement"
        render "new"
      end
  end

  def show
  end

  def annuaire_params
    params.require(:annuaire).permit(:num_dept, :nom_dpt, :commune, :email)
  end

  def get_id
    @annuaire = Annuaire.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :sanitize_devise_params, if: :devise_controller?

	def sanitize_devise_params
		devise_parameter_sanitizer.permit(:sign_up, keys:[:username])
	end
end

app/helpers/annuaire_helper.rb
module AnnuaireHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/annuaire/create.html.erb
<h1>Annuaire#create</h1>
<p>Find me in app/views/annuaire/create.html.erb</p>

app/views/annuaire/index.html.erb
<div class="container">
	<table class="table table-hover">
		<thead>
			<tr>
				<th scope="col">N° de département</th>
				<th scope="col">Nom de département</th>
				<th scope="col">Nom de commune</th>
				<th scope="col">Email du mairie</th>
				<th scope="col">Opérateur</th>
			</tr>
		</thead>
  		<tbody>
			<% @annuaires.each do |element| %>
	    	<tr class="table-active">
				<td><%= element.num_dept %></td>
				<td><%= element.nom_dpt %></td>
				<td><%= element.commune %></td>
				<td><%= element.email %></td>
				<td><%= User.find(element.user_id).username %></td> <!-- A remplacer par le créateur du post -->
			</tr>
			<% end %>
  		</tbody>
	</table>
</div>

app/views/annuaire/new.html.erb
<div class="container">
	<%= form_for @annuaire, url: annuaire_index_path do |f| %>
        <div class="form-group">
            <label for="num_dept">Numéro du département</label>
            <%= f.text_field :num_dept, class: "form-control form-control-lg" %>
        </div>

        <div class="form-group">
            <label for="nom_dpt">Nom du département</label>
            <%= f.text_area :nom_dpt, class: "form-control form-control-lg text-editor" %>
        </div>
    
        <div class="form-group">
            <label for="commune">Commune</label>
            <%= f.text_area :commune, class: "form-control form-control-lg text-editor" %>
        </div>

        <div class="form-group">
            <label for="email">Email</label>
            <%= f.text_area :email, class: "form-control form-control-lg text-editor" %>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-lg btn-primary">Créer l'annuaire</button>
        </div>
	<% end %>
</div>

app/views/annuaire/show.html.erb
<table>
	<tr>
		<td>Numero dept : <%= @annuaire.num_dept %></td>
	</tr>
	<tr>
		<td>Nom dept : <%= @annuaire.nom_dpt %></td>
	</tr>
	<tr>
		<td>Commune : <%= @annuaire.commune %></td>
	</tr>
	<tr>
		<td>Email : <%= @annuaire.email %></td>
	</tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BddAnnuaire</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- CSS Bootstrap -->
    <!-- <link rel="stylesheet" media="all" href="css/bootstrap.css"> -->
    <link rel="stylesheet" href="https://bootswatch.com/4/slate/bootstrap.css">
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
    <!-- CSS Bootstrap local -->

    <!-- Font awesome -->
    <link rel="stylesheet" href="css/all.css">
    <link rel="stylesheet" href="css/brands.css">
    <link rel="stylesheet" href="css/fontawesome.css">
    <link rel="stylesheet" href="css/regular.css">
    <link rel="stylesheet" href="css/solid.css">
    <link rel="stylesheet" href="css/svg-with-js.css">
    <link rel="stylesheet" href="css/v4-shims.css">


  </head>

  <body>
      <!-- NAVBAR -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="/">OPS ANNUAIRE</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
            </li>
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to 'Ajouter Annuaire', new_annuaire_path, class: "nav-link btn btn-outline-info" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete, class: "nav-link btn btn-outline-danger" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <a class="nav-link btn btn-outline-success" href="<%= new_user_session_path %>">Se connecter</a>
                </li>
              <li class="nav-item">
                <a class="nav-link btn btn-outline-info" href="<%= new_user_registration_path %>">S'enregistrer</a>
              </li>
              <% end %>
          </ul>

          <%= form_tag(root_path, method: :get, class: "form-inline my-2 my-lg-0") do %>
              <%= text_field_tag :term, params[:term], placeholder:"Opérateur", class: "form-control mr-sm-2" %>
              <%= submit_tag 'Search', name: nil, class: "btn btn-secondary my-2 my-sm-0" %>
          <% end %>
        </div>
      </nav>

        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <div class="container">
    <!-- Conteunu de la page -->
    <%= yield %>
</div>
    <!-- JS par défaut de rails -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- JS Bootstrap -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.2/js/all.js"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  </body>
</html>